### ISSUE TITLE
repo.rb recipe

### ISSUE THREAD

**Issue by agutierrezl** [rackspace-cookbooks/varnish#100]
The repo.rb recipe fails in a amazon linux ami. This is because the 'node['platform_version']' return something like this '' 2015.09' and it fails when creating the varnish.repo file.

**Comment by martinb3** [comment]
Hi @agutierrezl -- we're not currently testing on or supporting Amazon Linux, but we'd gladly review a PR or other enhancements to make this work on Amazon Linux. Thanks for the heads up!
