### ISSUE TITLE
vcl_source not part of any tag

### ISSUE THREAD

**Issue by scones** [rackspace-cookbooks/varnish#105]
the parameter 'vcl_source' from varnish_default_vcl.rb is committed to master, but the current master is untagged.

This yields a discrepancy between the documentation when visiting the gem and the actual gem when installing through the Cheffile.

So the request is: Please tag the current master with an updated version.

**Comment by martinb3** [comment]
Hello! What gem are you referring to?

**Comment by scones** [comment]
https://github.com/rackspace-cookbooks/varnish

branch: master
file: https://github.com/rackspace-cookbooks/varnish.rb

**Comment by martinb3** [comment]
Hello! The first link is to this cookbook (not a gem), and the second link is 404. If you're just referring to the cookbook, I'm happy to do a release, but I wanted to be sure we were talking about the same -- there shouldn't be any gem documentation anywhere that I'm aware of.

**Comment by scones** [comment]
Sorry, i mixed up the terminology.
Yes i meant this cookbook.

**Comment by martinb3** [comment]
I've released a v2.4.0. Thanks!

**Comment by scones** [comment]
No, thank you.
