### ISSUE TITLE
varnish 4 doesn't support user/group daemon options

### ISSUE THREAD

**Issue by stormf** [rackspace-cookbooks/varnish#112]
Varnish 4 does not support `-u` or `-g` daemon options. They are listed on the official docs, but not the man page, and using them results in:

```
 * Starting HTTP accelerator varnishd ... [fail]
/usr/sbin/varnishd: invalid option -- 'u'
```

Without these options varnish does run as an unprivileged user (`varnish` or `vcache`), but there is also a new option `-j jail[,jailoptions]`.

https://github.com/rackspace-cookbooks/varnish/blob/339b6542c19e769952a108d6a8a94807582c62f7/templates/default/default.erb#L27

**Comment by RyanJarv** [comment]
This should be fixed in the latest version on the chef supermarket.

**Comment by martinb3** [comment]
Gonna go ahead and close this. Please try the latest version and re-open if you encounter a problem.
