### ISSUE TITLE
Varnishlog no longer included in package.

### ISSUE THREAD

**Issue by RichieHowell** [rackspace-cookbooks/varnish#114]
It seems that varnish-cache has removed varnishlog from the varnish package (https://github.com/varnishcache/pkg-varnish-cache/commit/da5cfe2ec2d7e406c1a880942fc9ea2907b0b62) and the default recipe tries to start this service. Recipe should probably be updated to check for an init file before attempting to enable/start this service.

**Comment by martinb3** [comment]
We've made a bunch of changes here to the default recipe. Can  you retry and see if you're still experiencing this issue? If so, we'll re-open. Thank you!
