### ISSUE TITLE
ArgumentError - wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by deathowl** [rackspace-cookbooks/varnish#54]
Trace:

/tmp/packer-chef-solo/cookbooks-1/varnish/libraries/varnish_default_config.rb:
    ua-development:
    ua-development: 1:  class Chef
    ua-development: 2:    class Resource
    ua-development: 3:      # Configure the Varnish service.
    ua-development: 4:      class VarnishDefaultConfig < Chef::Resource::LWRPBase
    ua-development: 5>>       resource_name :varnish_default_config
    ua-development: 6:
    ua-development: 7:        actions :configure
    ua-development: 8:        default_action :configure
    ua-development: 9:
    ua-development: 10:        attribute :name, kind_of: String, name_attribute: true
    ua-development: 11:
    ua-development: 12:        # Service config options
    ua-development: 13:        attribute :start_on_boot, kind_of: [TrueClass, FalseClass],
    ua-development: 14:                                  default: true
    ua-development:
    ua-development: [2015-02-24T14:23:11+00:00] DEBUG: Re-raising exception: ArgumentError - wrong number of arguments (1 for 0)

**Comment by splisson-altair** [comment]
How did you solve the issue ?  I got the same

**Comment by deathowl** [comment]
@splisson-altair upgrade to chef 12
