### ISSUE TITLE
Adding Parameters to v3.0 breaks init script

### ISSUE THREAD

**Issue by fernandohonig** [rackspace-cookbooks/varnish#57]
When having these parameters by default:

    +                  -p thread_pools=4 \
    +                  -p thread_pool_min=5 \
    +                  -p thread_pool_max=500 \
    +                  -p thread_pool_timeout=300 \

It gives an error when trying to start varnish thru /etc/init.d/varnish

**Comment by mattjbarlow** [comment]
Hey there. Can you provide some more information about the error you are seeing? I just spun up the vendor-libraries-centos-65 test kitchen suite. Logged in and catted out `/etc/sysconfig/default` and verified that the parameters you listed are in there. I then ran `/etc/init.d/varnish stop` and `/etc/init.d/varnish start`. The service stopped and started successfully.

https://gist.github.com/mattjbarlow/7b54ea11aa261541b754

**Comment by fernandohonig** [comment]
Have you tried with version 3.0 as an attribute?

**Comment by mattjbarlow** [comment]
I'm assuming you mean the node attribute for the [varnish version](https://github.com/rackspace-cookbooks/varnish/blob/master/attributes/default.rb#L7)

I just ran this test: https://github.com/rackspace-cookbooks/varnish/blob/master/.kitchen.yml#L39-L46

With `kitchen converge varnish3-centos-65`. After the test, I verified that these parameters are set:

```
              -s file,/var/lib/varnish/$INSTANCE_varnish_storage.bin,1G \
                  -p thread_pools=4 \
                  -p thread_pool_min=5 \
                  -p thread_pool_max=500 \
                  -p thread_pool_timeout=300 \
              -S /etc/varnish/secret"
```
And the service restarted successfully. One thing I noticed is that the attribute is set to '3.0' not 'v3.0'. Could that be the problem?

Please let me know how to duplicate this issue using the kitchen suites.

**Comment by mattjbarlow** [comment]
@fernandohonig told me that it is working now, and may have been a problem on his side.
