### ISSUE TITLE
varnish_default_config has broken defaults

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/varnish#72]
In `default` recipe, the storage defaults are:
```
default['varnish']['storage_file'] = '/var/lib/varnish/$INSTANCE_varnish_storage.bin'
default['varnish']['storage_size'] = '1G'
```

In the `varnish_default_config`, the storage defaults are:
```
file_storage_path 	string 	nil
file_storage_size 	string 	'1G'
```

Varnish won't start with the defaults for the resource, as the syntax is:
```
    -s [name=]kind[,options]     # Backend storage specification
                                 #   -s malloc[,<size>]
                                 #   -s file  [default: use /tmp]
                                 #   -s file,<dir_or_file>
                                 #   -s file,<dir_or_file>,<size>
                                 #   -s file,<dir_or_file>,<size>,<granularity>
                                 #   -s persist{experimental}
```

You may not omit `<dir_or_file>` when you specify `<size>`. But the default resource does exactly this. On my centos-66 instance, `STORAGE=file,1G` in `/etc/sysconfig/varnish`.

Versions:
```
# rpm -qa | grep varnish
varnish-4.0.3-1.el6.x86_64
varnish-libs-4.0.3-1.el6.x86_64
```

**Comment by martinb3** [comment]
In short, it looks like the first branch of the if-statement is an invalid config with the current defaults:
```
<%- if @config.storage == 'file' %>
STORAGE=<%= [@config.storage, @config.file_storage_path, @config.file_storage_size].compact.join(",") %>
<%- else %>
STORAGE=<%= [@config.storage, @config.malloc_size].compact.join(",") %>
<% end %>
```
Since `file_storage_path` defaults to nil, the compact call removes the path element, producing the broken/bad line in the config --
```
      attribute :file_storage_path, kind_of: String,
                                    default: nil
```

produces:
```
STORAGE=file,1G
```

I propose we set the default file storage path to something real, so it's compatible with the other default value of file-based storage.

**Comment by mattjbarlow** [comment]
Nice find. The default file path `'/var/lib/varnish/$INSTANCE_varnish_storage.bin'` won't work for systems that use Systemd. Systemd uses the [varnish.params](https://github.com/rackspace-cookbooks/varnish/blob/d26012eb92ef4211431b86edf5b74b848f88f942/templates/default/lib_default_systemd.erb) file, which doesn't allow for insertion of bash-like variables in the value.

This is why the [fixture recipe](https://github.com/rackspace-cookbooks/varnish/blob/master/test/fixtures/cookbooks/install_varnish/recipes/distro_install.rb#L31-L35) checks for systemd and changes the storage path accordingly.

So, two options are 1) to default to malloc, or 2) we could look at adding a systemd drop-in as a template, which would override the `[Service]` inside the package unit file. However, if we go with the drop-in approach, it means maintaining unit file that could conflict with the upstream package in the future. What do you think? Is there another alternative?

**Comment by martinb3** [comment]
I ended up hard-coding a file path as the default, though I know that won't work for multiple instances (not sure if the resources/providers herein support that completely anyway, though). See #73 for my workaround.
