### ISSUE TITLE
node['varnish']['conf_cookbook'] not honored in LWRP

### ISSUE THREAD

**Issue by jhmartin** [rackspace-cookbooks/varnish#77]
node['varnish']['conf_cookbook'] is not honored / no equivalent is available when invoking the LWRP varnish_default_config, nor is the equivalent for generated vcl.

**Comment by RyanJarv** [comment]
Version 3.0.0 added this as a global attribute so it should work using the configure recipe or resources now. It can also be overridden with the conf_cookbook property on the varnish_default resource.
