### ISSUE TITLE
Centos 6.6 Repo is incorrect

### ISSUE THREAD

**Issue by mikeyhill** [rackspace-cookbooks/varnish#78]
What Chef installs w/ this cookbook:

    [varnish]
    name=Varnish 3.0.7 repo (6.6 - $basearch)
    baseurl=http://repo.varnish-cache.org/redhat/varnish-3.0.7/el6/
    enabled=1
    gpgcheck=0
    gpgkey=http://repo.varnish-cache.org/debian/GPG-key.txt
    sslverify=true

This produces 404 errors that the package does not exist.  By running the rpm recommend by Varnish here (https://www.varnish-cache.org/installation/redhat) a yum.repos.d/varnish.repo is produced like this:

    [varnish-3.0]
    name=Varnish 3.0 for Enterprise Linux el6 - $basearch
    baseurl=http://repo.varnish-cache.org/redhat/varnish-3.0/el6/$basearch
    enabled=1
    gpgcheck=0
    #gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-VARNISH

This then allows the installation of Varnish 3.0.7 to succeed.  I will work on a pull request for this.

**Comment by martinb3** [comment]
Hi there -- using the `varnish3-centos-66` test suite from this cookbook, I get `/etc/yum.repos.d/varnish.repo`:

```
# This file was generated by Chef
# Do NOT modify this file by hand.

[varnish]
name=Varnish 3.0 repo (6.6 - $basearch)
baseurl=http://repo.varnish-cache.org/redhat/varnish-3.0/el6/
enabled=1
gpgcheck=0
gpgkey=http://repo.varnish-cache.org/debian/GPG-key.txt
sslverify=true
```

Perhaps you're using a recipe I'm not. Could you share how you're invoking this cookbook? Maybe you're using different attributes with the LWRP, or calling the recipe differently?

**Comment by mikeyhill** [comment]
Actually, I need to close this.  There's a recipe in there (::repo) to include before you call the main varnish recipe that will put the correct repo's in place.
