### ISSUE TITLE
NilClass error on attributes

### ISSUE THREAD

**Issue by delianides** [rackspace-cookbooks/varnish#81]
I know this can be a common error in chef if attributes aren't found but I can't seem to get it resolved. This is the output at the end of the chef run.

```
==> default: [2015-08-05T17:58:17+00:00] INFO: Starting Chef Run for noah-berkshelf
==> default: [2015-08-05T17:58:17+00:00] INFO: Running start handlers
==> default: [2015-08-05T17:58:17+00:00] INFO: Start handlers complete.
==> default: /tmp/vagrant-chef/ce43313c9572ad145ac7ec26866e5732/cookbooks/homebrew/libraries/homebrew_package.rb:26: warning: toplevel constant Homebrew referenced by Chef::Provider::Package::Homebrew
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error in /tmp/vagrant-chef/ce43313c9572ad145ac7ec26866e5732/cookbooks/varnish/attributes/default.rb
==> default: ================================================================================
==> default:
==> default:
==> default: NoMethodError
==> default: -------------
==> default: undefined method `[]=' for nil:NilClass
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:
==> default:   /tmp/vagrant-chef/ce43313c9572ad145ac7ec26866e5732/cookbooks/varnish/attributes/default.rb:2:in `from_file'
==> default:
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /tmp/vagrant-chef/ce43313c9572ad145ac7ec26866e5732/cookbooks/varnish/attributes/default.rb:
==> default:
==> default:   1:  if platform_family?('debian')
==> default:   2>>   default['varnish']['default'] = '/etc/default/varnish'
==> default:   3:  else
==> default:   4:    default['varnish']['default'] = '/etc/sysconfig/varnish'
==> default:   5:  end
==> default:   6:
==> default:   7:  default['varnish']['version'] = '4.0'
==> default:   8:
==> default:   9:  default['varnish']['dir'] = '/etc/varnish'
==> default:  10:  default['varnish']['start'] = 'yes'
==> default:  11:  default['varnish']['nfiles'] = 131_072
==> default:
==> default:
==> default:
==> default: [2015-08-05T17:58:18+00:00] ERROR: Running exception handlers
==> default: [2015-08-05T17:58:18+00:00] ERROR: Exception handlers complete
==> default: [2015-08-05T17:58:18+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-08-05T17:58:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

I've tried everything, copying the cookbook locally to make sure it was included correctly. I even copied the attributes into a brand new cookbook skeleton and made the default recipe just `puts` one of the attributes. Whats even stranger is that if I change the root name of the attribute, ```[varnish]``` to something else; it works. 

I've using the ChefDK, Vagrant and Berkshelf, but dropping the chef version to 11.6 which matches the version Rightscale is using. 

I'm requiring this cookbook (at the 1.0.2 version) in the metadata and including it in a separate recipe. Its the same way I'm installing/configuring apache, php and nodejs and i don't have any issues with those cookbooks.

**Comment by martinb3** [comment]
Hi there -- I just checked out v1.0.2, created test kitchen suites with chef 11.18.12 and 11.16.4 and varnish (v3 and v4), and I was able to successfully converge successfully. Is it possible you're using chefspec or testing with chef-solo or something else? I can't reproduce this.

We're going to need a self-contained, reproducible example to really be able to help you further.

**Comment by delianides** [comment]
Locally I'm using chef-solo. However, I did try converging in Rightscale and it was successful so I'm thinking its an issue with chef-solo. It's confusing because, I have other cookbooks that I'm loading and don't have the same issues. Still investigating. Thanks!

**Comment by martinb3** [comment]
Just searching around on Google, the most common cause of this in chef-solo is a missing `depends 'varnish'` in your cookbook's `metadata.rb` file. Can you confirm that's in place?

**Comment by delianides** [comment]
I have included the `depends` in the metadata but still no change.

**Comment by martinb3** [comment]
> We're going to need a self-contained, reproducible example to really be able to help you further. 

Sorry @delianides, I'm just not sure what else to do to help you reproduce this. We may need a workable example that causes the problem.

**Comment by martinb3** [comment]
Going to close this, as I haven't heard anything back. I'm not sure we can do much to help since we can't reproduce and it appears to be specific to chef-solo and very strange that the Chef Mash would complain about a missing key.
