### ISSUE TITLE
Service resource start failures - Chef run continues

### ISSUE THREAD

**Issue by yoshiwaan** [rackspace-cookbooks/varnish#84]
I have found that when using the Varnish cookbook > 2.0.0 (when the varnish logging library was added) causes service resources in a Chef run to not cause an exception and end a chef run on a start or restart failure. The root cause is alteration to the service resource using a prepended module which alters the behavior of the service.

https://github.com/rackspace-cookbooks/varnish/pull/83 points to the problem and how to possibly fix it.

**Comment by martinb3** [comment]
Closing since #83 was merged. Releasing now.

**Comment by yoshiwaan** [comment]
Thank you
