### ISSUE TITLE
instance_name defaults and fallback

### ISSUE THREAD

**Issue by dzabel** [rackspace-cookbooks/varnish#90]
prerequisites:
- if node['fqdn'] and node['hostname'] are different
- node['varnish']['instance'] uses default value (node['fqdn'])
- now use the log_varnish ressource and define no instance_name.

what happens? 
because instance_name is not defined for lwrp, the template uses node['hostname'] as fallback which is not the same as node['fqdn']. service varnishlog cannot be startetd because files can't be found.

**Comment by RyanJarv** [comment]
All the resources and recipes use node['hostname'] by default now so this should be fixed in 3.0.0. Let me know if you are still running into this with the latest version.
