### ISSUE TITLE
Varnish doesn't install on Chef 12.5

### ISSUE THREAD

**Issue by jujugrrr** [rackspace-cookbooks/varnish#93]
I'm using the resource `varnish_install`, somehow it doesn't install the `varnish` package anymore on hte new Chef version.

All good with `12.4.3`

**Comment by martinb3** [comment]
I'm guessing this has fixed it -- https://github.com/rackspace-cookbooks/varnish/commit/41b797447074bbb0767525e18fc815d20e39c3c7.

**Comment by martinb3** [comment]
I'm going to close this, but we definitely need to fix up this cookbook in a long term, sustainable way.
